---
config:
  look: neo
  theme: redux
  layout: dagre
---
classDiagram
direction LR  
   namespace Domain.Models {
        class Course {
            +Id: int
            +Name: string
            +Description: string
            +Status: CourseStatus
            +LearningOutcomes: List<LearningOutcome>
       }

       class LearningOutcome {
            +Id: int
            +CourseId: string
            +Name: string
            +Description: string
            +EndQualification: string
            +Course: Course
            +Lessons: List<Lessons>?
       }
    }

    namespace Domain.Enums {
        class CourseStatus{
            <<enumeration>>
            Concept
            Validated
        }
    }

%% Relations
    Course --> CourseStatus : has status
    Course --> LearningOutcome
    LearningOutcome --> Course
    LearningOutcome --> Lesson