---
config:
  look: neo
  theme: redux
  layout: dagre
---
classDiagram
direction LR
    namespace Server.Controllers {
        class ControllerBase {
            <<external>>
        }

        class BaseApiController {
            <<abstract>>
            #HandleResponse~T~(Response~T~ response, bool noContentOnSuccess) IActionResult
            #HandleCreatedResponse~T~(Response~T~ response, string actionName, object routeValues) IActionResult
        }

        class CourseController {
            -ICourseService courseService
            -ILearningOutcomeService learningOutcomeService
            +CourseController(ICourseService courseService, ILearningOutcomeService learningOutcomeService)
            +GetAll() Task~IActionResult~
            +Get(int id) Task~IActionResult~
            +GetLearningOutcomesByCourseId(int id) Task~IActionResult~
            +Create(CreateCourseDto dto) Task~IActionResult~
            +Update(int id, UpdateCourseDto dto) Task~IActionResult~
            +Delete(int id) Task~IActionResult~
        }

        class LearningOutcomeController {
            -ILearningOutcomeService learningOutcomeService
            +CourseController(ILearningOutcomeService learningOutcomeService)
            +GetAll() Task~IActionResult~
            +Get(int id) Task~IActionResult~
            +Create(CreateLearningOutcome createLearningOutcome) Task~IActionResult~
            +Update(int id, UpdateLearningOutcome updateLearningOutcome) Task~IActionResult~
            +Delete(int id) Task~IActionResult~
        }
    }


    namespace Core.Dto{
        class CourseDto {
            <<external>>
        }

        class CreateCourseDto {
            <<external>>
        }

        class UpdateCourseDto {
            <<external>>
        }

        class LearningOutcomeDto {
            <<external>>
        }

        class CreateLearningOutcomeDto {
            <<external>>
        }

        class UpdateLearningOutcomeDto {
            <<external>>
        }
    }

    namespace Core.Interfaces.Services{
        class ICourseService {
            <<external>>
        }

        class ILearningOutcomeService {
            <<external>>
        }
    }

    %% Base Controller
    BaseApiController --|> ControllerBase : inherits
    CourseController --|> BaseApiController : inherits
    LearningOutcomeController --|> BaseApiController : inherits

    %% Course
    CourseController --> ICourseService : delegates to
    CourseController --> ILearningOutcomeService : delegates to
    CourseController ..> CreateCourseDto : receives
    CourseController ..> UpdateCourseDto : receives
    CourseController ..> CourseDto : returns

    %% LearningOutcome
    LearningOutcomeController --> ILearningOutcomeService : delegates to
    LearningOutcomeController ..> CreateLearningOutcomeDto : receives
    LearningOutcomeController ..> UpdateLearningOutcomeDto : receives
    LearningOutcomeController ..> LearningOutcomeDto : returns